version: "3.3"
services:
  ansible:
    container_name: automate-cloud-vpn
    env_file: 
      - "env_vars"
    volumes:
      - ./project:/project
      - ./terraform.tfstate.bak:/terraform/terraform.tfstate
    image: albeanski/ansible-terraform-aws:latest
