version: "3.3"
services:
  app:
    volumes:
      - wg-client-config:/wireguard/client

  testing:
    container_name: automate-cloud-vpn-testing
    cap_add:
      - NET_ADMIN
      - SYS_MODULE
    volumes:
      - wg-client-config:/wireguard
    image: albeanski/wireguard:latest

volumes:
  wg-client-config:
