version: "3.3"
services:
  app:
    container_name: automate-cloud-vpn
    env_file: 
      - "env_vars"                      # private environment variables
    environment:
      - TERRAFORM_AUTO_APPROVE=false    # change this to 'true' for full automation
    volumes:
      - ./project:/project
      - ./terraform.tfstate:/terraform/terraform.tfstate
    image: albeanski/ansible-terraform-aws-wg:latest
