---
# Adapted from: https://jawher.me/wireguard-ansible-systemd-ubuntu/
#          and: https://dev.to/tangramvision/exploring-ansible-via-setting-up-a-wireguard-vpn-3389
#
# tasks file for wireguard_client_create_interface_config
- name: Create client wireguard interface config
  ansible.builtin.template:
    dest: "{{ wireguard_runtime_dir }}/client_wg0.conf"
    src: "{{ wireguard_template_dir }}/client_wg0.conf"
    mode: '0600'
