---
ssh_public_key:    "{{ lookup('ansible.builtin.env', 'SSH_PUBLIC_KEY',    default='/ssh_keys/ssh_key.pub') }}"
ssh_private_key:   "{{ lookup('ansible.builtin.env', 'SSH_PRIVATE_KEY',   default='/ssh_keys/ssh_key') }}"

aws_instance_name: "{{ lookup('ansible.builtin.env', 'AWS_INSTANCE_NAME') | mandatory }}"
aws_instance_type: "{{ lookup('ansible.builtin.env', 'AWS_INSTANCE_TYPE', default='t2.micro') }}"
aws_access_key:    "{{ lookup('ansible.builtin.env', 'AWS_ACCESS_KEY')    | mandatory }}"
aws_secret_key:    "{{ lookup('ansible.builtin.env', 'AWS_SECRET_KEY')    | mandatory }}"
aws_instance_ami:  "{{ lookup('ansible.builtin.env', 'AWS_INSTANCE_AMI')  | mandatory }}"
aws_region:        "{{ lookup('ansible.builtin.env', 'AWS_REGION')        | mandatory }}"
aws_user:          "{{ lookup('ansible.builtin.env', 'AWS_USER')          | mandatory }}"

wireguard_server_ip: "{{ lookup('ansible.builtin.env', 'WIREGUARD_SERVER_IP', default='10.11.12.1/24') }}"
wireguard_client_ip: "{{ lookup('ansible.builtin.env', 'WIREGUARD_CLIENT_IP', default='10.11.12.2/24') }}"
wireguard_subnet: "{{ lookup('ansible.builtin.env', 'WIREGUARD_SUBNET', default='10.11.12.0/24') }}"
wireguard_port: "{{ lookup('ansible.builtin.env', 'WIREGUARD_PORT', default='51820') }}"

ansible_user: "{{ aws_user }}"

aws_security_groups:
  - name: ssh
    id: ssh
    vpc: selected
    ingresses:
      - name: SSH
        from_port: 22
        to_port: 22
        protocol: "tcp"
        cidr_blocks:
          - 0.0.0.0/0

      - name: Wireguard
        from_port: "{{ wireguard_port }}"
        to_port: "{{ wireguard_port }}"
        protocol: "udp"
        cidr_blocks:
          - 0.0.0.0/0

    tags:
      - ["Name", "SSH"]

