---
ssh_public_key:    "{{ lookup('ansible.builtin.env', 'SSH_PUBLIC_KEY',    default='/project/files/ssh_key.pub') }}"
ssh_private_key:   "{{ lookup('ansible.builtin.env', 'SSH_PRIVATE_KEY',   default='/project/files/ssh_key') }}"

aws_instance_type: "{{ lookup('ansible.builtin.env', 'AWX_INSTANCE_TYPE', default='t2.micro') }}"
aws_access_key:    "{{ lookup('ansible.builtin.env', 'AWS_ACCESS_KEY')    | mandatory }}"
aws_secret_key:    "{{ lookup('ansible.builtin.env', 'AWS_SECRET_KEY')    | mandatory }}"
aws_instance_ami:  "{{ lookup('ansible.builtin.env', 'AWS_INSTANCE_AMI')  | mandatory }}"
aws_region:        "{{ lookup('ansible.builtin.env', 'AWS_REGION')        | mandatory }}"
aws_user:          "{{ lookup('ansible.builtin.env', 'AWS_USER)           | mandatory }}"

aws_security_groups:
  - name: ssh
    id: ssh
    vpc: selected
    ingresses:
      - name: SSH
        from_port: 22
        to_port: 22
        protocol: "tcp"
        cidr_blocks:
          - 0.0.0.0/0

    tags:
      - ["Name", "SSH"]
