---
# tasks file for wireguard_server_system_setup
- name: enable and persist ip forwarding
  become: yes
  ansible.builtin.sysctl:
    name: net.ipv4.ip_forward
    value: "1"
    state: present
    sysctl_set: yes
    reload: yes
