- hosts: aws_ec2
  roles:
    - role: wireguard_install
    - role: wireguard_server_system_setup
    - role: wireguard_server_create_keys

- hosts: localhost
  roles:
    - role: wireguard_client_create_keys

# Wireguard public and private keys must be created first because interfaces reference both server and client keys
# then we can create the interfaces below
- hosts: localhost
  roles:
    - role: wireguard_client_create_interface_config

- hosts: aws_ec2
  roles:
    - role: wireguard_server_create_interface_config
    - role: wireguard_server_start

