#!/bin/bash
dockerfiles_prefix="tags/dockerfiles"
tags=$(git tag)
if [ ! -z "$tags" ]; then
  for t in "${tags[@]}"; do
    echo "$t"
    if [[ "$t" =~ "${dockerfiles_prefix}/ansible/" ]]; then
      version="$(echo "$t" | grep -oe "[^/]*$")"
      echo "New version found: "
    fi
  done
fi
