---
# vars file for wireguard_client_create_keys
wireguard_template_dir: templates/wireguard
wireguard_runtime_dir: /wireguard

wireguard_client_privatekey_file: "{{ wireguard_runtime_dir }}/client_privatekey"
wireguard_client_publickey_file: "{{ wireguard_runtime_dir }}/client_publickey"
